version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: appraisal-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: appraisal_db
      MYSQL_USER: appraisal_user
      MYSQL_PASSWORD: appraisal1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appraisal-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mysql_data:

networks:
  appraisal-network:
    driver: bridge
